# Generated by Django 4.2.30 on 2026-09-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='amenities',
            field=models.TextField(blank=True, default=''),
        ),
    ]
